const THROTTLER_WINDOW_PERIOD = 60; // in seconds
const THROTTLER_NUMBER_OF_REQUESTS = 100;
const API_BASE_PATH = '/v1';

const PAGINATION_DEFAULT_PAGE = 1;
const PAGINATION_DEFAULT_LIMIT = 100;

const SENTRY_DEFAULT_SAMPLE_RATE = 0.25;
const SENTRY_DEFAULT_TRACE_SAMPLE_RATE = 0.2;
// eslint-disable-next-line no-shadow
const enum CONFIG_KEYS {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    CORS_WHITELIST = 'CORS_WHITELIST',
    TYPEORM_HOST = 'TYPEORM_HOST',
    TYPEORM_USERNAME = 'TYPEORM_USERNAME',
    TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
    TYPEORM_DATABASE = 'TYPEORM_DATABASE',
    TYPEORM_PORT = 'TYPEORM_PORT',
    TYPEORM_LOGGING = 'TYPEORM_LOGGING',
    TYPEORM_DDL_SYNC = 'TYPEORM_DDL_SYNC',
    AUTH0_DOMAIN = 'AUTH0_DOMAIN',
    AUTH0_TENANT_DOMAIN = 'AUTH0_TENANT_DOMAIN',
    AUTH0_AUDIENCE = 'AUTH0_AUDIENCE',
    MACHINE_TOKEN = 'MACHINE_TOKEN',
    MACHINE_IPS = 'MACHINE_IPS',
    WITH_DOCS = 'WITH_DOCS',
    SENTRY_DSN = 'SENTRY_DSN',
    SENTRY_LOGGING = 'SENTRY_LOGGING',
    SENTRY_SAMPLE_RATE = 'SENTRY_SAMPLE_RATE',
    SENTRY_TRACES_SAMPLE_RATE = 'SENTRY_TRACES_SAMPLE_RATE',
    RABBITMQ_URI = 'RABBITMQ_URI',
    LOG_LEVEL = 'LOG_LEVEL',
    SWAGGER_USER = 'SWAGGER_USER',
    SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',
    REDIS_URL = 'REDIS_URL',
    OTLP_COLLECTOR_URL = 'OTLP_COLLECTOR_URL',
}

export {
    THROTTLER_WINDOW_PERIOD,
    THROTTLER_NUMBER_OF_REQUESTS,
    API_BASE_PATH,
    CONFIG_KEYS,
    PAGINATION_DEFAULT_LIMIT,
    PAGINATION_DEFAULT_PAGE,
    SENTRY_DEFAULT_SAMPLE_RATE,
    SENTRY_DEFAULT_TRACE_SAMPLE_RATE,
};
